routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ContactController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/post', [PostController::class, 'index'])->name('post');
Route::post('/create-post', [PostController::class, 'store'])->name('post.save');


// Create Client
    // Route::get('client',[ClientController::class,'index'])->name('client');
    // Route::get('client/create',[ClientController::class,'create'])->name('client.create');
    // Route::get('client/{client}/edit',[ClientController::class,'edit'])->name('client.edit');
    // Route::post('client/store',[ClientController::class,'store'])->name('client.store');
    // Route::put('client/{client}',[ClientController::class,'update'])->name('client.update');
    // Route::post('client/{client}',[ClientController::class,'destroy'])->name('client.destroy');

    Route::resource('clients', ClientController::class);

// Manage Contact
Route::get('contact',[ContactController::class,'index'])->name('contact');
Route::get('contact/create',[ContactController::class,'create'])->name('contact.create');
Route::post('contact/store',[ContactController::class,'store'])->name('contact.store');

// Configure for File Manager
Route::group(['prefix' => 'filemanager', 'middleware' => ['web']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/Client.php
<?php

namespace App\Models;

use Spatie\MediaLibrary\HasMedia;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\InteractsWithMedia;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Client extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia;

    protected $fillable = [
        'name',
        'email',
    ];
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::latest()->get();
        return view('clients.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $client = Client::create($input);

        if($request->hasFile('avatar') && $request->file('avatar')->isValid()){

            $client->addMediaFromRequest('avatar')->toMediaCollection('client');
        }
        return redirect()->route('clients.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::find($id);

        return view('clients.edit',compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required'
        ]);
        // $input = $request->all();

        $client = Client::find($id);
        $client->name = $request->name;
        $client->email = $request->email;
        $client->save();

        if ($client) {
            if ($request->hasFile('avatar')) {
                $client->clearMediaCollection('client');
                $client->addMediaFromRequest('avatar')->toMediaCollection('client');
            }
        }

        session()->flash('success', 'Client Update successfully');

        return redirect()->route('clients.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $client = Client::find($id);
        $client->delete();

        session()->flash('success', 'Client Delete successfully');

        return redirect()->route('clients.index');
    }
}

resources/views/clients/create.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Add Spatie Medialibrary in Laravel</title>
    @include('includes.custom_header')
</head>

<body class="bg-white">
    @include('includes.navbar')

    <div class="container text-black">
        <div class="row justify-content-md-center">
            <div class="col-md-6">
                <div class="d-flex p-2 bg-white mb-3">
                    <a href="{{ route('clients.index') }}" class="btn btn-primary btn-sm">Go Back</a>
                </div>
                <div>
                    <h3>Create Client</h3>
                    <form action="{{ route('clients.store') }}" enctype="multipart/form-data" method="post">
                        {{-- @csrf --}}
                        {{ csrf_field() }}
                        <div class="mb-3">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control">
                        </div>
                        <div class="mb-3">
                            <label>Email</label>
                            <input type="email" name="email" class="form-control">
                        </div>
                        <div class="mb-3">
                            <label>Image:</label>
                            <input type="file" name="avatar" class="form-control">
                        </div>
                        <div class="d-grid">
                            <button class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
            </div>


        </div>



    </div>
</body>

</html>

resources/views/clients/edit.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Add Spatie Medialibrary in Laravel</title>
    @include('includes.custom_header')
</head>

<body class="bg-white">
    @include('includes.navbar')

    <div class="container text-black">
        <div class="row justify-content-md-center">
            <div class="col-md-6">
                <div class="d-flex p-2 bg-white mb-3">
                    <a href="{{ route('clients.index') }}" class="btn btn-primary btn-sm">Go Back</a>
                </div>
                <div>
                    <h3>Edit Update Client</h3>
                    <form action="{{ route('clients.update',$client->id) }}" enctype="multipart/form-data" method="post">
                        @csrf
                        @method('put')

                        <div class="mb-3">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" value="{{$client->name}}">
                        </div>
                        <div class="mb-3">
                            <label>Email</label>
                            <input type="email" name="email" class="form-control" value="{{$client->email}}">
                        </div>
                        <div class="mb-3">
                            <label>Image:</label>
                            <input type="file" name="avatar" class="form-control">
                        </div>
                        <div class="d-grid">
                            <button class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
            </div>


        </div>



    </div>
</body>

</html>

resources/views/clients/index.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Integrate Spatie Medialibrary in Laravel</title>
    @include('includes.custom_header')
</head>

<body>
    @include('includes.navbar')

    <div class="container">
        <div class="p-2 bd-highlight"><h3>List of Client</h3></div>
        <div class="d-flex flex-row-reverse bd-highlight">
            <div class="p-12 bd-highlight">
                <a class="btn btn-success" href="{{route('clients.create')}}">Create</a>
            </div>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th width="30%">Avatar</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Option</th>
                </tr>
            </thead>
            <tbody>
                @foreach($clients as $key=>$item)
                <tr>
                    <td>{{ ++$key }}</td>
                    <td><img style="border-radius: 60px; height:60px !important;" class="img-thumbnail" src="{{$item->getFirstMediaUrl('client', 'thumb')}}" / width="60px" height="60px" ></td>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->email }}</td>
                    <td>
                        <a class="btn btn-xs btn-primary" href="{{ route('clients.edit',$item->id) }}">
                            Edit
                        </a>
                        <form action="{{ route('clients.destroy',$item->id) }}" method="POST" onsubmit="return confirm('{{ trans('are You Sure ? ') }}');"
                                            style="display: inline-block;">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <input type="submit" class="btn btn-xs btn-danger" value="Delete">
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</html>