routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ContactController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/post', [PostController::class, 'index'])->name('post');
Route::post('/create-post', [PostController::class, 'store'])->name('post.save');


// Create Client
    // Route::get('client',[ClientController::class,'index'])->name('client');
    // Route::get('client/create',[ClientController::class,'create'])->name('client.create');
    // Route::get('client/{client}/edit',[ClientController::class,'edit'])->name('client.edit');
    // Route::post('client/store',[ClientController::class,'store'])->name('client.store');
    // Route::put('client/{client}',[ClientController::class,'update'])->name('client.update');
    // Route::post('client/{client}',[ClientController::class,'destroy'])->name('client.destroy');

    Route::resource('clients', ClientController::class);

// Manage Contact
Route::get('contact',[ContactController::class,'index'])->name('contact');
Route::get('contact/create',[ContactController::class,'create'])->name('contact.create');
Route::post('contact/store',[ContactController::class,'store'])->name('contact.store');

// Configure for File Manager
Route::group(['prefix' => 'filemanager', 'middleware' => ['web']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

resources/views/includes/custom_header.blade.php
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css"
    rel="stylesheet" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hanuman:wght@300;400;700;900&display=swap" rel="stylesheet">

    <link rel="shortcut icon" type="image/png" href="{{ asset('vendor/laravel-filemanager/img/72px color.png') }}">

<style>
    .bootstrap-tagsinput .tag {
        margin-right: 2px;
        color: #ffffff;
        background: #2196f3;
        padding: 3px 7px;
        border-radius: 3px;
    }

    .bootstrap-tagsinput {
        width: 100%;
    }

    .limited-text{
        white-space: nowrap;
        width: 100%;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .limited-title{
        white-space: nowrap;
        width: 100%;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .img-post {
        width: 100%;
        height: 145px;
        object-fit: cover;
        object-position: bottom;
    }
    body{
        font-family: 'Hanuman', serif !important;
        font-weight: 400;
    }
    .card-title{
        font-family: 'Hanuman', serif !important;
        font-weight: 700;
    }


    /* For Scrolling */

    /* width */
        ::-webkit-scrollbar {
        width: 10px;
        }

        /* Track */
        ::-webkit-scrollbar-track {
        box-shadow: inset 0 0 5px grey;
        border-radius: 10px;
        }

        /* Handle */
        ::-webkit-scrollbar-thumb {
        background: rgb(2, 144, 68);
        border-radius: 10px;
        }

        /* Handle on hover */
        ::-webkit-scrollbar-thumb:hover {
        background: #b30000;
        }



        /* Menu Custom */
        .nav-pills .nav-link {
            background: 0 0 !important;

            border: 0;
            border-radius: 0px !important;
            /* color: white !important; */
        }

        .nav-pills .nav-link.active, .nav-pills .show>.nav-link {
            color: rgb(253, 251, 251);
            /* background-color: #0d6efd; */
            background: 0 0 !important;

        }

        .img-contact {
            width: 100%;
            height: 145px;
            object-fit: cover;
            object-position: bottom;
        }

        .banner {
            align-items: center;
            background-color: #002ead !important;
            color: var(--gray00);
            /* display: flex;
            font-size: 14px;
            font-weight: 700;
            justify-content: center;
            padding: 8px;
            position: fixed;
            text-decoration: none;
            top: var(--header-height);
            width: 100vw; */
            z-index: 999;
        }
        .image-upload > input {
            visibility:hidden;
            width:0;
            height:0
        }

</style>

resources/views/includes/navbar.blade.php
 <header>
    <div class="bg-dark">
        <div class="container-fluid d-none d-lg-block">
            <div class="row justify-content-md-center pt-2">
                <div class="col-4" style="text-align: center;">
                    <img height="96px" src="{{asset('images/sourng_web_dev.png')}}">
                </div>
                <div class="col-8"><img src="{{asset('images/banner_top.jpg')}}" alt=""></div>
            </div>
        </div>
    </div>

    <nav id="navbar_top" class="navbar navbar-expand-lg navbar-dark bg-info banner">
     <div class="container">
          <a class="navbar-brand" href="/"><img height="34px" src="{{asset('images/sourng_web_dev.png')}}" alt=""></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main_nav">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="main_nav">
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a class="nav-link {{ (request()->is('post')) ? 'active' : '' }}" aria-current="page" href="{{route('post')}}">Posts</a>
              </li>
              <li class="nav-item">
                {{-- <a class="nav-link {{ (request()->is('client')) ? 'active' : '' }}" aria-current="page" href="{{route('client')}}">Clients</a> --}}
                <a class="nav-link {{ (request()->is('clients')) ? 'active' : '' }}" href="{{route('clients.index')}}">Clients</a>
            </li>
              <li class="nav-item">
                <a class="nav-link {{ (request()->is('contact')) ? 'active' : '' }}" href="{{route('contact')}}">Contact</a>
            </li>

        </ul>
      </div> <!-- navbar-collapse.// -->
     </div> <!-- container-fluid.// -->
    </nav>
    </header>